#!/usr/bin/env python3
"""Score a labelled WILD corpus through the shipped inference, for honest eval.

The wild test set is the project's missing safety net: real transcodes collected
from the wild (not generated by our own ffmpeg pipeline), plus known-authentic
files, that the model has **never seen** and that don't share our synthetic
pipeline's tells. Running it through the *shipped* inference
(:func:`...ml_classifier.infer_file_probability`, multi-window + calibration) and
feeding the output to ``ml/measure_auc_drop.py`` tells you whether the 0.94 AUC on
held-out ffmpeg data survives contact with reality.

Two ways to point it at the corpus:

* ``--manifest manifest.csv`` — a CSV with ``path,label[,source]`` rows (label
  1=transcoded, 0=authentic; optional free-text ``source`` e.g. "soulseek",
  "lame3.100", "itunes"). Paths may be relative to ``--root``.
* ``--authentic DIR --transcoded DIR`` — label by directory, like emit_probs.

Output CSV columns: ``path,label,source,p_raw,p_cal,rolloff,abstained`` — richer
than emit_probs (which is just the calibration-fit input) because evaluation wants
the diagnostics too. ``measure_auc_drop.py`` reads the p_raw/label columns.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import List, Tuple

from flac_detective.analysis.new_scoring.rules.ml_classifier import infer_file_probability

_AUDIO_EXTS = {".flac", ".wav", ".m4a", ".ape"}


def _from_manifest(manifest: Path, root: Path) -> List[Tuple[Path, int, str]]:
    """Read (path, label, source) rows from a manifest CSV."""
    rows: List[Tuple[Path, int, str]] = []
    with open(manifest, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            raw = row.get("path", "").strip()
            if not raw:
                continue
            path = (root / raw) if not Path(raw).is_absolute() else Path(raw)
            rows.append((path, int(row.get("label", 0)), row.get("source", "").strip()))
    return rows


def _from_dirs(authentic: Path, transcoded: Path) -> List[Tuple[Path, int, str]]:
    """Build (path, label, source) rows from an authentic/transcoded dir split."""
    rows: List[Tuple[Path, int, str]] = []
    for root, label in ((authentic, 0), (transcoded, 1)):
        if root is None:
            continue
        for p in sorted(root.rglob("*")):
            if p.is_file() and p.suffix.lower() in _AUDIO_EXTS:
                rows.append((p, label, root.name))
    return rows


def main() -> None:
    """Score the wild corpus and write the evaluation CSV."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", type=Path, help="CSV with path,label[,source] rows")
    ap.add_argument("--root", type=Path, default=Path("."), help="Base dir for relative paths")
    ap.add_argument("--authentic", type=Path, help="Directory of authentic files (label 0)")
    ap.add_argument("--transcoded", type=Path, help="Directory of transcoded files (label 1)")
    ap.add_argument("--out", type=Path, required=True, help="Output CSV path")
    args = ap.parse_args()

    if args.manifest:
        rows = _from_manifest(args.manifest, args.root)
    elif args.authentic or args.transcoded:
        rows = _from_dirs(args.authentic, args.transcoded)
    else:
        raise SystemExit("Pass --manifest or --authentic/--transcoded.")
    if not rows:
        raise SystemExit("No files found.")

    written = skipped = 0
    with open(args.out, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["path", "label", "source", "p_raw", "p_cal", "rolloff", "abstained"])
        for i, (path, label, source) in enumerate(rows, 1):
            if not path.is_file():
                skipped += 1
                continue
            result = infer_file_probability(path)
            if result is None:
                skipped += 1
                continue
            writer.writerow(
                [
                    str(path),
                    label,
                    source,
                    f"{result['p_raw']:.6f}",
                    f"{result['p_cal']:.6f}",
                    f"{result['rolloff']:.0f}",
                    int(result["abstained"]),
                ]
            )
            written += 1
            if i % 100 == 0:
                print(f"  {i}/{len(rows)} ({written} written, {skipped} skipped)")

    print(f"Wrote {written} rows to {args.out} ({skipped} skipped).")
    print("Next: python ml/measure_auc_drop.py baseline=ffmpeg_probs.csv wild=" + str(args.out))


if __name__ == "__main__":
    main()
